# Site settings
title: 逆流的技术博客
email: helloworldismytag@hotmail.com
description: > #你逆流技术博客
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: ""
github_username: ""


# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 逆流
  email: helloworldismytag@hotmail.com
  link: 
  weibo: 
  github: 
title: 逆流的技术博客                             #自定义常量

# avatar头像及Favicon
avatar: 

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

ba:
  src: 

# disqus 设置
disqus:
  shortname: helloworldismytag